export const SET_MANAGE_TOKEN = 'SET_MANAGE_TOKEN'

export const SET_MANAGE_USER_INFO = 'SET_MANAGE_USER_INFO'

export const SET_MANAGE_ACCOUNT = 'SET_MANAGE_ACCOUNT'

export const SET_MANAGE_USERID = 'SET_MANAGE_USERID'

export const SET_MANAGE_AUTH = 'SET_MANAGE_AUTH'

export const SET_MENU = 'SET_MENU'
